/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedGalleryIndexRouteImport } from './routes/_authenticated/gallery/index'
import { Route as AuthenticatedEventIndexRouteImport } from './routes/_authenticated/event/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCategoryArticleIndexRouteImport } from './routes/_authenticated/category-article/index'
import { Route as AuthenticatedCareerIndexRouteImport } from './routes/_authenticated/career/index'
import { Route as AuthenticatedArticleIndexRouteImport } from './routes/_authenticated/article/index'
import { Route as AuthenticatedEventCreateRouteImport } from './routes/_authenticated/event/create'
import { Route as AuthenticatedEventIdRouteImport } from './routes/_authenticated/event/$id'
import { Route as AuthenticatedCategoryArticleCreateRouteImport } from './routes/_authenticated/category-article/create'
import { Route as AuthenticatedCategoryArticleIdRouteImport } from './routes/_authenticated/category-article/$id'
import { Route as AuthenticatedCareerCreateRouteImport } from './routes/_authenticated/career/create'
import { Route as AuthenticatedCareerIdRouteImport } from './routes/_authenticated/career/$id'
import { Route as AuthenticatedArticleCreateRouteImport } from './routes/_authenticated/article/create'
import { Route as AuthenticatedArticleIdRouteImport } from './routes/_authenticated/article/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGalleryIndexRoute =
  AuthenticatedGalleryIndexRouteImport.update({
    id: '/gallery/',
    path: '/gallery/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventIndexRoute = AuthenticatedEventIndexRouteImport.update({
  id: '/event/',
  path: '/event/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoryArticleIndexRoute =
  AuthenticatedCategoryArticleIndexRouteImport.update({
    id: '/category-article/',
    path: '/category-article/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCareerIndexRoute =
  AuthenticatedCareerIndexRouteImport.update({
    id: '/career/',
    path: '/career/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArticleIndexRoute =
  AuthenticatedArticleIndexRouteImport.update({
    id: '/article/',
    path: '/article/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventCreateRoute =
  AuthenticatedEventCreateRouteImport.update({
    id: '/event/create',
    path: '/event/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventIdRoute = AuthenticatedEventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoryArticleCreateRoute =
  AuthenticatedCategoryArticleCreateRouteImport.update({
    id: '/category-article/create',
    path: '/category-article/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoryArticleIdRoute =
  AuthenticatedCategoryArticleIdRouteImport.update({
    id: '/category-article/$id',
    path: '/category-article/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCareerCreateRoute =
  AuthenticatedCareerCreateRouteImport.update({
    id: '/career/create',
    path: '/career/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCareerIdRoute = AuthenticatedCareerIdRouteImport.update({
  id: '/career/$id',
  path: '/career/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArticleCreateRoute =
  AuthenticatedArticleCreateRouteImport.update({
    id: '/article/create',
    path: '/article/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArticleIdRoute = AuthenticatedArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/article/$id': typeof AuthenticatedArticleIdRoute
  '/article/create': typeof AuthenticatedArticleCreateRoute
  '/career/$id': typeof AuthenticatedCareerIdRoute
  '/career/create': typeof AuthenticatedCareerCreateRoute
  '/category-article/$id': typeof AuthenticatedCategoryArticleIdRoute
  '/category-article/create': typeof AuthenticatedCategoryArticleCreateRoute
  '/event/$id': typeof AuthenticatedEventIdRoute
  '/event/create': typeof AuthenticatedEventCreateRoute
  '/article': typeof AuthenticatedArticleIndexRoute
  '/career': typeof AuthenticatedCareerIndexRoute
  '/category-article': typeof AuthenticatedCategoryArticleIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/event': typeof AuthenticatedEventIndexRoute
  '/gallery': typeof AuthenticatedGalleryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/article/$id': typeof AuthenticatedArticleIdRoute
  '/article/create': typeof AuthenticatedArticleCreateRoute
  '/career/$id': typeof AuthenticatedCareerIdRoute
  '/career/create': typeof AuthenticatedCareerCreateRoute
  '/category-article/$id': typeof AuthenticatedCategoryArticleIdRoute
  '/category-article/create': typeof AuthenticatedCategoryArticleCreateRoute
  '/event/$id': typeof AuthenticatedEventIdRoute
  '/event/create': typeof AuthenticatedEventCreateRoute
  '/article': typeof AuthenticatedArticleIndexRoute
  '/career': typeof AuthenticatedCareerIndexRoute
  '/category-article': typeof AuthenticatedCategoryArticleIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/event': typeof AuthenticatedEventIndexRoute
  '/gallery': typeof AuthenticatedGalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/article/$id': typeof AuthenticatedArticleIdRoute
  '/_authenticated/article/create': typeof AuthenticatedArticleCreateRoute
  '/_authenticated/career/$id': typeof AuthenticatedCareerIdRoute
  '/_authenticated/career/create': typeof AuthenticatedCareerCreateRoute
  '/_authenticated/category-article/$id': typeof AuthenticatedCategoryArticleIdRoute
  '/_authenticated/category-article/create': typeof AuthenticatedCategoryArticleCreateRoute
  '/_authenticated/event/$id': typeof AuthenticatedEventIdRoute
  '/_authenticated/event/create': typeof AuthenticatedEventCreateRoute
  '/_authenticated/article/': typeof AuthenticatedArticleIndexRoute
  '/_authenticated/career/': typeof AuthenticatedCareerIndexRoute
  '/_authenticated/category-article/': typeof AuthenticatedCategoryArticleIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/event/': typeof AuthenticatedEventIndexRoute
  '/_authenticated/gallery/': typeof AuthenticatedGalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/article/$id'
    | '/article/create'
    | '/career/$id'
    | '/career/create'
    | '/category-article/$id'
    | '/category-article/create'
    | '/event/$id'
    | '/event/create'
    | '/article'
    | '/career'
    | '/category-article'
    | '/dashboard'
    | '/event'
    | '/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/article/$id'
    | '/article/create'
    | '/career/$id'
    | '/career/create'
    | '/category-article/$id'
    | '/category-article/create'
    | '/event/$id'
    | '/event/create'
    | '/article'
    | '/career'
    | '/category-article'
    | '/dashboard'
    | '/event'
    | '/gallery'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/article/$id'
    | '/_authenticated/article/create'
    | '/_authenticated/career/$id'
    | '/_authenticated/career/create'
    | '/_authenticated/category-article/$id'
    | '/_authenticated/category-article/create'
    | '/_authenticated/event/$id'
    | '/_authenticated/event/create'
    | '/_authenticated/article/'
    | '/_authenticated/career/'
    | '/_authenticated/category-article/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/event/'
    | '/_authenticated/gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gallery/': {
      id: '/_authenticated/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/event/': {
      id: '/_authenticated/event/'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof AuthenticatedEventIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/category-article/': {
      id: '/_authenticated/category-article/'
      path: '/category-article'
      fullPath: '/category-article'
      preLoaderRoute: typeof AuthenticatedCategoryArticleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/career/': {
      id: '/_authenticated/career/'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof AuthenticatedCareerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/article/': {
      id: '/_authenticated/article/'
      path: '/article'
      fullPath: '/article'
      preLoaderRoute: typeof AuthenticatedArticleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/event/create': {
      id: '/_authenticated/event/create'
      path: '/event/create'
      fullPath: '/event/create'
      preLoaderRoute: typeof AuthenticatedEventCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/event/$id': {
      id: '/_authenticated/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof AuthenticatedEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/category-article/create': {
      id: '/_authenticated/category-article/create'
      path: '/category-article/create'
      fullPath: '/category-article/create'
      preLoaderRoute: typeof AuthenticatedCategoryArticleCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/category-article/$id': {
      id: '/_authenticated/category-article/$id'
      path: '/category-article/$id'
      fullPath: '/category-article/$id'
      preLoaderRoute: typeof AuthenticatedCategoryArticleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/career/create': {
      id: '/_authenticated/career/create'
      path: '/career/create'
      fullPath: '/career/create'
      preLoaderRoute: typeof AuthenticatedCareerCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/career/$id': {
      id: '/_authenticated/career/$id'
      path: '/career/$id'
      fullPath: '/career/$id'
      preLoaderRoute: typeof AuthenticatedCareerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/article/create': {
      id: '/_authenticated/article/create'
      path: '/article/create'
      fullPath: '/article/create'
      preLoaderRoute: typeof AuthenticatedArticleCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/article/$id': {
      id: '/_authenticated/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof AuthenticatedArticleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedArticleIdRoute: typeof AuthenticatedArticleIdRoute
  AuthenticatedArticleCreateRoute: typeof AuthenticatedArticleCreateRoute
  AuthenticatedCareerIdRoute: typeof AuthenticatedCareerIdRoute
  AuthenticatedCareerCreateRoute: typeof AuthenticatedCareerCreateRoute
  AuthenticatedCategoryArticleIdRoute: typeof AuthenticatedCategoryArticleIdRoute
  AuthenticatedCategoryArticleCreateRoute: typeof AuthenticatedCategoryArticleCreateRoute
  AuthenticatedEventIdRoute: typeof AuthenticatedEventIdRoute
  AuthenticatedEventCreateRoute: typeof AuthenticatedEventCreateRoute
  AuthenticatedArticleIndexRoute: typeof AuthenticatedArticleIndexRoute
  AuthenticatedCareerIndexRoute: typeof AuthenticatedCareerIndexRoute
  AuthenticatedCategoryArticleIndexRoute: typeof AuthenticatedCategoryArticleIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedEventIndexRoute: typeof AuthenticatedEventIndexRoute
  AuthenticatedGalleryIndexRoute: typeof AuthenticatedGalleryIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArticleIdRoute: AuthenticatedArticleIdRoute,
  AuthenticatedArticleCreateRoute: AuthenticatedArticleCreateRoute,
  AuthenticatedCareerIdRoute: AuthenticatedCareerIdRoute,
  AuthenticatedCareerCreateRoute: AuthenticatedCareerCreateRoute,
  AuthenticatedCategoryArticleIdRoute: AuthenticatedCategoryArticleIdRoute,
  AuthenticatedCategoryArticleCreateRoute:
    AuthenticatedCategoryArticleCreateRoute,
  AuthenticatedEventIdRoute: AuthenticatedEventIdRoute,
  AuthenticatedEventCreateRoute: AuthenticatedEventCreateRoute,
  AuthenticatedArticleIndexRoute: AuthenticatedArticleIndexRoute,
  AuthenticatedCareerIndexRoute: AuthenticatedCareerIndexRoute,
  AuthenticatedCategoryArticleIndexRoute:
    AuthenticatedCategoryArticleIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedEventIndexRoute: AuthenticatedEventIndexRoute,
  AuthenticatedGalleryIndexRoute: AuthenticatedGalleryIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
